# Add application configuration variables here, as shown below.

# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

defaults: &defaults
  # Settings
  GRUVID_EMAIL: hi@gruvid.com
  GRUVID_URL: http://gruvid.herokuapp.com
  BLENDER_URL: http://ec2-54-154-6-34.eu-west-1.compute.amazonaws.com
  
  # Amazon S3
  AWS_KEY: AKIAJWPSHM6LB7HAVAGQ
  AWS_SECRET: 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
  # Apple Push Notifications
  APN_HOST: gateway.push.apple.com
  APN_PORT: 2195
  #APN_PEM_FILE: app/assets/certificates/apnProd.pem
  #APN_PASSWORD: Dingo123
  
development:
  <<: *defaults
  AWS_BUCKET: gruvid-test
  
test:
  <<: *defaults
  AWS_BUCKET: gruvid-test
  
production:
  <<: *defaults
  # Amazon S3
  AWS_BUCKET: gruvid-prod
  
  # Apple Push Notifications
  #APN_HOST: gateway.push.apple.com
  #APN_PORT: 2195
  #APN_PEM_FILE: app/assets/certificates/apnProd.pem
  #APN_PASSWORD: Dingo123
