# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a84cf112f8c1535063be5d9c53b5193ed3a748884c78096761a164a20a3821c76bf7bc3ba6e8f71a93c4204bdea303127ec134e2675e0668970fba3aaabe52b

test:
  secret_key_base: 1cc3b335d75a82ed2e76e45d34296aa28944730549f17bd52b80b3aec8377f8c0c9f7dcc9131fad0bdb619bdb47244e295fa59e4fdb97f24cad6f3c9a07734c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
